### PR TITLE
NO-ISSUE add SKIPPER_PLATFORM variable

### PR DESCRIPTION
**Pull request by michaellevy101**

### CODE REVIEW

**Comment by eranco74** [comment]
What is it good for?

**Comment by michaellevy101** [comment]
We have a networking issue for macos but i can't identify what's the actual platform.
It's possible to add this variable to the skipper-mac.yaml file but IMO adding it the skipper itself is better
The actual case is: 
Running skipper make deploy-test which deploy assisted-service on my minikube
After the deployment this target validating the installation and trying to connect to the service
The service is deployed on host and unaccessible from the skipper container.
This is an only MACOS issue since the 'host' network is not supported (please see:https://docs.docker.com/network/host/)
To resolve this issue we have to identify the platform and change the URL to 'host.docker.internal'
For example:

    if os.getenv("SKIPPER_PLATFORM") == 'darwin':
        url = urlparse(health_url)

        if url.hostname == "127.0.0.1":
            url._replace(netloc=f"host.docker.internal:{url.port}")
            health_url = urlunsplit(url)


It's possible to change the URL to host.docker.internal not only for MAC users but i don't want to affect other platforms and i can't test it

**Comment by eranco74** [comment]
Seems that skipper itself has no use for this env, so I don't think it belongs in skipper.

**Comment by michaellevy101** [comment]
Skipper exposes this info to the container...  Skipper is the only connection with the os
It's like python exposing the os information to the programmer
If skipper is a platform to run a make builds and the builds need this data. why not?

**Comment by eranco74** [comment]
I think it's arbitrary and is relevant only due to some implementation detail of some code executed inside the container (not relevant to skipper).
Since it's relevant just for specific application (and not for skipper implementation) this env should be defined in the skipper.yaml of that environment.

**Comment by michaellevy101** [comment]
Skipper uses Docker or podman to run the containers and Docker behave differently on each platform.
The case i described is not a specific applicative case or implementation detail but an example to a generic docker issue (Docker For Desktop does not support 'host' network).
This is not the first case where this information required
anyway, do you suggest creating a dedicated skipper file per platform?

**Comment by eranco74** [comment]
I think a way around it is to use the [env-file](https://github.com/Stratoscale/skipper#environment-variables) option.
Pretty sure the env file doesn't need to be part of the project.

**Comment by eranco74** [comment]
Stale issue, closing

**Pull request closed without merging**
