### PR TITLE
Add runtime command (podman/docker...) environment variable

### PR DESCRIPTION
**Pull request by michaellevy101**

### CODE REVIEW

**Comment by eranco74** [comment]
Where is RUNTIME_COMMAND used?

**Comment by michaellevy101** [comment]
> RUNTIME_COMMAND

The container should use it to decide how to create containers/build 
For example the container might have docker and podman installed and use the right command by this variable.
Basically It's an information about the underline system which the container can use and make decisions according to it. 
There is big difference between a container runs on docker which shares the socket and podman which creates a new storage for the container which should affect the build logic
For example using this podman specific capability:
https://coreos.slack.com/archives/G01A5NB3S6M/p1629703561177900
Or using docker experimental features

**Comment by tsorya** [comment]
sounds good to me. @eranco74 it can be very helpful to know which command was used

**Comment by eranco74** [comment]
I agree, it can be very useful.
But it's irrelevant for skipper.
If someone want to add this env to his skipper.yaml no one is stopping him.

**Comment by michaellevy101** [comment]
> I agree, it can be very useful.
> But it's irrelevant for skipper.
> If someone want to add this env to his skipper.yaml no one is stopping him.

because it's automatic instead of setting it manually like:
export CONTAINER_COMMAND=podman/docker
In addition if you don't specify which tool to use and you have them both (podman and docker) the tool is selected automatically without any human interaction... please see the selection code https://github.com/Stratoscale/skipper/blob/257223bf4dbe931320f77cce1c805bcf99cd86a3/skipper/utils.py#L159

**Comment by eranco74** [comment]
> > I agree, it can be very useful.
> > But it's irrelevant for skipper.
> > If someone want to add this env to his skipper.yaml no one is stopping him.
> 
> because it's automatic instead of setting it manually like:
> export CONTAINER_COMMAND=podman/docker
> In addition if you don't specify which tool to use and you have them both (podman and docker) the tool is selected automatically without any human interaction... please see the selection code
> 
> https://github.com/Stratoscale/skipper/blob/257223bf4dbe931320f77cce1c805bcf99cd86a3/skipper/utils.py#L159

You can achieve the same automatic behavior by adding this to your skipper.yaml:
```
env:
    RUNTIME_COMMAND: $(which docker || which podman)
```
The above should work with skipper version 1.31.0

**Comment by michaellevy101** [comment]
> The above should work with skipper version 1.31.0

not working... changed the env variable name according to your comment and updated the readme file

**Comment by eranco74** [comment]
> > The above should work with skipper version 1.31.0
> 
> not working... changed the env variable name according to your comment and updated the readme file

```
 15:34:54 >skipper version
1.31.0
15:35:01 > cat skipper.yaml | grep RUNTIME
RUNTIME_COMMAND: $(which docker || which podman)
 15:35:10 > skipper shell
[skipper] No build container tag was provided
[skipper] Building image using docker file: Dockerfile.assisted-service-build
Sending build context to Docker daemon  76.18MB
Step 1/7 : FROM registry.ci.openshift.org/openshift/release:golang-1.16
 ---> 784484e27a9c
Step 2/7 : ENV GO111MODULE=on
 ---> Using cache
 ---> 4d47fcba91aa
Step 3/7 : ENV GOFLAGS=""
 ---> Using cache
 ---> cf4ac3d0e681
Step 4/7 : COPY ./hack/setup_env.sh ./dev-requirements.txt ./
 ---> Using cache
 ---> eb280481aec1
Step 5/7 : RUN ./setup_env.sh assisted_service
 ---> Using cache
 ---> e0127063b49a
Step 6/7 : COPY --from=quay.io/openshift/origin-cli:latest /usr/bin/oc /usr/bin
 ---> Using cache
 ---> eaa71862a7e9
Step 7/7 : COPY --from=quay.io/operator-framework/upstream-opm-builder:v1.16.1 /bin/opm /bin
 ---> Using cache
 ---> 23cf47da07fb
Successfully built 23cf47da07fb
Successfully tagged assisted-service-build:latest
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
bash-4.2$ echo $RUNTIME_COMMAND 
/usr/bin/docker
bash-4.2$ 
```

**Review by eranco74 — APPROVED** [review]

**Pull request merged**
