### PR TITLE
os environ for keep containers for jenkins usage

### PR DESCRIPTION
**Pull request by igal-stratoscale**
@ravidbro @Stratoscale/cm @Stratoscale/systegration please look

### CODE REVIEW

**Comment by roeigo-stratoscale** [comment]
I am not sure this is a complete solution.
Dead containers can also harm the slave when they pile up (take storage/network spaces, etc...)

**Comment by ravidbro** [comment]
we are counting on meltwater to remove the dead containers

**Comment by rom-stratoscale** [comment]
@ravidbro are u pushing?

**Comment by ravidbro** [comment]
To master? I approved the PR. I didn't open it

**Comment by ravidbro** [comment]
@igal-stratoscale , can we push that?

**Comment by igal-stratoscale** [comment]
@ravidbro yap, thanks

**Pull request merged**
