### PR TITLE
Romang/py3 compatability

### PR DESCRIPTION
**Pull request by romang-stratoscale**

### CODE REVIEW

**Comment by ravidbro** [comment]
And it works only when using python 2?

**Comment by romang-stratoscale** [comment]
@ravidbro I tested and ran it in both py2 and py3 envs

**Comment by romang-stratoscale** [comment]
@eran-stratoscale please review

**Comment by romang-stratoscale** [comment]
@ravidbro how can I integrate this?

**Comment by ravidbro** [comment]
@romang-stratoscale  just rebase and push to master, I will push it

**Comment by ravidbro** [comment]
published as 1.8.6

**Pull request merged**
